- block:
        - name: "Checking Java Rpm Locally"
          shell: "ls jdk-java.rpm"
          args:
               chdir: "/root"
          changed_when: false
  rescue:
          - name: "Installing Required dependencies"
            package:
               name:
                 - "python3"
                 - "python2-pip"
          - name: "Installing other Dependencies"
            pip:
              name: gdown
              executable: pip3
          - name: "Downloading Java Rpm File from Gdrive"
            shell: "/usr/local/bin/gdown --id {{ jdk_id }}"
            args:
               chdir: "/root"

- block:
     - name: "Checking Hadoop Rpm Locally"
       shell: "ls hadoop.rpm"
       args:
               chdir: "/root"
       changed_when: false
  rescue:
     - name: "Downloading Hadoop Rpm File from Gdrive"
       shell: "/usr/local/bin/gdown --id {{ hadoop_id }}"
       args:
               chdir: "/root"
- name: "Installing Java"
  package:
       name: "/root/jdk-java.rpm"
       state: present
- name: "Checking hadoop and installing"
  block:
       - name: "Checking hadoop"
         command: "rpm -q hadoop"
         changed_when: False
  rescue:
      - name: "Installing hadoop"
        command: "rpm -i hadoop.rpm --force"
        args:
                chdir: "/root"
      - name: "Configuring Hadoop Jobtracker"
        template:
              src: "{{ item }}"
              dest: "/etc/hadoop"

        loop:
             - "mapred-site.xml"
        notify:
            - "start hadoop-jt"

