- block:
     - shell: "ls jdk-java.rpm"
       changed_when: false
  rescue:
     - package:
         name:
            - "python3"
            - "python2-pip"
     - pip:
         name: gdown
         executable: pip3
     - shell: "gdown --id {{ jdk_id }}"

- block:
     - shell: "ls"
     - shell: "ls hadoop.rpm"
       changed_when: false
  rescue:
     - shell: "gdown --id {{ hadoop_id }}"
- name: "Copy Installing file"
  copy:
        src: "{{ item }}"
        dest: "/root"

  loop:
                    - "hadoop-1.2.1-1.x86_64.rpm"
                    - "jdk-8u171-linux-x64.rpm"
                    
- name: "Installing Java"
  package:
       name: "jdk-8u171-linux-x64.rpm"
       state: present
- name: "Checking hadoop and installing"
  block:
       - name: "Checking hadoop"
         command: "rpm -q hadoop"
         changed_when: False
  rescue:
      - name: "Installing hadoop"
        command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
        args:
                chdir: "/root"
      - name: "Configuring Hadoop Namenode"
        template:
              src: "{{ item }}"
              dest: "/etc/hadoop"

        loop:
             - "hdfs-site.xml"
             - "core-site.xml"
        notify:
            - "Creating Namenode Directory"
            - "Format hadoop dir"
            - "start hadoop"

